name: basic tests

on:
  push:
    branches:
      - "user/**"
      - "feature/**"
      - "improvement/**"
      - "bugfix/**"
      - "w/**"
      - "q/**"
      - "hotfix/**"
      - "dependabot/**"
  pull_request:
    types:
      - opened

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
